Catch fail when calling mock with unknown args

diff --git a/mock b/mock
--- a/mock
+++ b/mock
@@ -26,6 +26,10 @@ if [ ! -e mocks/${command} ]; then
 
 
 funame=p_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
+if ! type "\${funame}" > /dev/null 2>&1; then
+    >&2 echo "ERROR: \$0 \$@ is not mocked"
+    exit 1
+fi
 \$funame
 EOF
 else
