Fix red marker in generated mock code

diff --git a/mockmaker b/mockmaker
--- a/mockmaker
+++ b/mockmaker
@@ -29,7 +29,7 @@ if [ ! -e mocks/${command_file} ]; then
 # For command: ${command_file}
 funame=p_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
 if ! type "\${funame}" > /dev/null 2>&1; then
-    >&2 echo "ERROR: \$0 \$@ is not mocked"
+    >&2 echo "ERROR: \$0 \$* is not mocked"
     exit 1
 fi
 \$funame
